### ISSUE TITLE
locale command is needed

### ISSUE THREAD

**Issue by paolobenve** [pmetras/mps_debian#1]
the last commits in myphotoshare's development branch require the locale command

**Comment by pmetras** [comment]
The scanner cron job in `/etc/cron.daily/myphotoshare` is using the locale as defined in `/etc/default/myphotoshare`.

But that's true that the `/usr/bin/myphotoshare_*` commands use the locale defined by user `myphotoshare`, usually 'C' or 'UTF-8'. They are not supposed to be run interactively by other users.

**Comment by paolobenve** [comment]
excuse me, _locate_, not _locale_

**Comment by pmetras** [comment]
Sorry but I don't understand either what to do with `locate`... A few explanations would help.

**Comment by paolobenve** [comment]
https://linux.die.net/man/1/locate

The dependency must be added

**Comment by pmetras** [comment]
I know `locate` but I don't understand how the new myphotoshare depends on it. And depending on the type of dependency, it can be a strong dependency or only a suggestion for installation.

**Comment by paolobenve** [comment]
`locate` is needed if opencv is installed, because the scanner needs to know where two relevant files for face and eye detection are in the filesystem

**Comment by pmetras** [comment]
OK. I've added `locate` as a suggested install like `opencv`.
I think it is installed by default on Debian distributions as a dependency of `man` and similar tools.
